# Generated by Django 3.2.4 on 2021-06-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_roll', models.CharField(max_length=10)),
                ('batch_session', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_1', to='users.subjectsmodel')),
                ('subject_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_2', to='users.subjectsmodel')),
                ('subject_3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_3', to='users.subjectsmodel')),
                ('subject_4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_4', to='users.subjectsmodel')),
                ('subject_5', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_5', to='users.subjectsmodel')),
                ('subject_6', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_6', to='users.subjectsmodel')),
                ('subject_optional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_optional', to='users.subjectsmodel')),
            ],
        ),
    ]
